
name: lab10

on: [push, pull_request]

jobs:
  bandit-sast:
    name: Run Bandit SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: bandit -r pygoat -f json -o bandit_report.json
        continue-on-error: true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_report.json

  docker-scout-scan:
    name: Docker Scout CVE Scan
    runs-on: ubuntu-latest
    needs: bandit-sast

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pygoat:test .
          docker push ${{ secrets.DOCKER_USERNAME }}/pygoat:test

      - name: Run Docker Scout CVE Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKER_USERNAME }}/pygoat:test
          only-severities: critical,high
          ignore-unfixed: true
          sarif-file: sarif
          output: scout-results.sarif

      - name: Upload Docker Scout Report
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-report
          path: scout-results.sarif
